# Generated by Django 3.0.3 on 2020-03-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutors',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tutors',
            name='qualifications',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tutors',
            name='slug',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tutors',
            name='university',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tutors',
            name='videoslug',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
