# Generated by Django 3.0.3 on 2020-03-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0002_auto_20200315_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutors',
            name='slug',
            field=models.SlugField(default=12312312),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutors',
            name='videoslug',
            field=models.SlugField(),
        ),
    ]
