# Generated by Django 3.0.3 on 2020-07-12 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentmemberships', '0004_remove_studentmembership_parents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutors', '0003_auto_20200315_1151'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tutors',
            new_name='EnglishTutors',
        ),
        migrations.CreateModel(
            name='FutureTutors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('slug', models.SlugField()),
                ('videoslug', models.SlugField()),
                ('qualifications', models.CharField(max_length=500, null=True)),
                ('university', models.CharField(max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
