# Generated by Django 3.1.1 on 2020-09-24 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0003_auto_20200905_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePlay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.IntegerField(verbose_name='Current Score')),
                ('current_position', models.IntegerField(verbose_name='Current Score')),
                ('level', models.IntegerField(verbose_name='Current Score')),
                ('money', models.IntegerField(verbose_name='Current Score')),
                ('weapons', models.IntegerField(verbose_name='Current Score')),
                ('student', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
