# Generated by Django 3.0.3 on 2020-03-17 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('studentmemberships', '0003_studentmembership_parents'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishGrades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocab', models.IntegerField()),
                ('grammar', models.IntegerField()),
                ('content', models.IntegerField()),
                ('creativity', models.IntegerField()),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='courses.EnglishLesson')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='studentmemberships.StudentMembership')),
            ],
        ),
    ]
