# Generated by Django 3.0.3 on 2020-03-17 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishgrades',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='courses.EnglishLesson'),
        ),
        migrations.AlterField(
            model_name='englishgrades',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FutureGrades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocab', models.IntegerField()),
                ('grammar', models.IntegerField()),
                ('content', models.IntegerField()),
                ('creativity', models.IntegerField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='courses.FutureLesson')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
