# Generated by Django 3.0.3 on 2020-03-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_auto_20200317_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='englishgrades',
            name='upload',
            field=models.FileField(blank=True, upload_to='user_directory_path'),
        ),
        migrations.AddField(
            model_name='englishgrades',
            name='upload_corrected',
            field=models.FileField(blank=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
