# Generated by Django 3.0.3 on 2020-03-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_auto_20200318_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishgrades',
            name='content',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='englishgrades',
            name='creativity',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='englishgrades',
            name='grammar',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='englishgrades',
            name='vocab',
            field=models.IntegerField(blank=True),
        ),
    ]
