# Generated by Django 3.0.3 on 2020-03-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0007_auto_20200318_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='englishgrades',
            name='comments',
            field=models.TextField(null=True),
        ),
    ]
