# Generated by Django 3.0.3 on 2020-07-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0008_englishgrades_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futuregrades',
            name='content',
        ),
        migrations.RemoveField(
            model_name='futuregrades',
            name='grammar',
        ),
        migrations.RemoveField(
            model_name='futuregrades',
            name='vocab',
        ),
        migrations.AddField(
            model_name='futuregrades',
            name='collaboration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='futuregrades',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='futuregrades',
            name='communication',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='futuregrades',
            name='critical_thinking',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='futuregrades',
            name='leadership',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='futuregrades',
            name='social_cultural_awareness',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='futuregrades',
            name='creativity',
            field=models.IntegerField(null=True),
        ),
    ]
