# Generated by Django 3.0.10 on 2021-02-01 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FutureStudentMembershipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('future_membership_type', models.CharField(choices=[('Smile School Future Full', 'Future Full'), ('Smile School Future Basic', 'Future Basic'), ('No Smile School Future', 'Future No')], default='No Smile School Future', max_length=30)),
                ('price', models.IntegerField(default=15)),
                ('stripe_plan_id', models.CharField(max_length=40)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(max_length=40)),
                ('futuremembership', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studentmemberships.FutureStudentMembershipType')),
                ('futuretutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tutors.FutureTutor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentFutureSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(max_length=40)),
                ('active', models.BooleanField(default=False)),
                ('futuremembershiptype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentmemberships.StudentMembership')),
            ],
        ),
        migrations.CreateModel(
            name='StudentEnglishSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(max_length=40)),
                ('active', models.BooleanField(default=False)),
                ('englishmembershiptype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentmemberships.StudentMembership')),
            ],
        ),
    ]
