# Generated by Django 3.0.3 on 2020-03-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmemberships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmembership',
            name='videoslug',
            field=models.SlugField(default='1'),
            preserve_default=False,
        ),
    ]
