# Generated by Django 3.0.3 on 2020-03-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmemberships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futurestudentmembershiptype',
            name='future_membership_type',
            field=models.CharField(choices=[('Smile School Future', 'Future'), ('No Smile School Future', 'Future No')], default='No Smile School Future', max_length=30),
        ),
    ]
