# Generated by Django 3.0.3 on 2020-03-16 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
        ('studentmemberships', '0002_studentmembership_videoslug'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmembership',
            name='parents',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parents.Parent'),
        ),
    ]
