# Generated by Django 3.0.3 on 2020-03-04 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentmemberships', '0002_auto_20200304_0424'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentSubscription',
            new_name='StudentEnglishSubscription',
        ),
        migrations.AlterField(
            model_name='studentenglishsubscription',
            name='englishmembershiptype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentmemberships.EnglishStudentMembershipType'),
        ),
        migrations.CreateModel(
            name='StudentFutureSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(max_length=40)),
                ('active', models.BooleanField(default=False)),
                ('englishfututretype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentmemberships.FutureStudentMembershipType')),
            ],
        ),
    ]
