# Generated by Django 3.0.3 on 2020-03-08 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentmemberships', '0003_auto_20200304_0439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentfuturesubscription',
            old_name='englishfututretype',
            new_name='fututremembershiptype',
        ),
    ]
