# Generated by Django 3.0.3 on 2020-07-12 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentmemberships', '0003_studentmembership_parents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmembership',
            name='parents',
        ),
    ]
