# Generated by Django 3.0.3 on 2020-07-12 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0004_auto_20200712_1355'),
        ('studentmemberships', '0004_remove_studentmembership_parents'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmembership',
            name='futuretutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tutors.FutureTutors'),
        ),
        migrations.AlterField(
            model_name='futurestudentmembershiptype',
            name='future_membership_type',
            field=models.CharField(choices=[('Smile School Future Full', 'Future Full'), ('Smile School Future Basic', 'Future Basic'), ('No Smile School Future', 'Future No')], default='No Smile School Future', max_length=30),
        ),
    ]
