# Generated by Django 3.0.3 on 2020-03-10 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentmemberships', '0005_auto_20200308_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenglishsubscription',
            name='englishmembershiptype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentmemberships.StudentMembership'),
        ),
        migrations.AlterField(
            model_name='studentfuturesubscription',
            name='futuremembershiptype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentmemberships.StudentMembership'),
        ),
    ]
