# Generated by Django 3.0.3 on 2020-03-16 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ParentMembershipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('parent_membership_type', models.CharField(choices=[('Smile School Parents', 'Parent'), ('No Smile School Parents', 'Parent No')], default='No Smile School Parents', max_length=30)),
                ('price', models.IntegerField(default=15)),
                ('stripe_plan_id', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ParentSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(max_length=40)),
                ('active', models.BooleanField(default=False)),
                ('parentmembershiptype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parents.ParentMembership')),
            ],
        ),
        migrations.AddField(
            model_name='parentmembership',
            name='parentmembership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parents.ParentMembershipType'),
        ),
        migrations.AddField(
            model_name='parentmembership',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent1', models.CharField(max_length=50, null=True)),
                ('parent2', models.CharField(max_length=50, null=True)),
                ('parentuseraccount', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
