# Generated by Django 3.0.3 on 2020-03-02 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_remove_user_following'),
        ('homelanding', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Connection',
        ),
    ]
