# Generated by Django 3.0.3 on 2020-03-03 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homelanding', '0004_auto_20200303_0700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsubscription',
            old_name='user_membership',
            new_name='student_membership',
        ),
        migrations.AlterField(
            model_name='studentmembership',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
