# Generated by Django 3.0.3 on 2020-03-03 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homelanding', '0005_auto_20200303_0719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmembershiptypes',
            name='slug',
        ),
        migrations.AlterField(
            model_name='parentmembership',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parentmembershiptypes',
            name='membership_type',
            field=models.CharField(choices=[('SmileSchoolParentSupport', 'Parent Plan'), ('None', 'No Plan')], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='studentmembership',
            name='membership',
            field=models.ForeignKey(default='None', null=True, on_delete=django.db.models.deletion.SET_NULL, to='homelanding.StudentMembershipTypes'),
        ),
        migrations.AlterField(
            model_name='studentmembershiptypes',
            name='membership_type',
            field=models.CharField(choices=[('SmileSchoolEnglishFull', 'Full Plan'), ('SmileSchoolFuture', 'Future Plan'), ('SmileSchoolBasic', 'Basic Plan'), ('None', 'No Plan')], default='None', max_length=30),
        ),
    ]
