# Generated by Django 3.0.3 on 2020-03-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelanding', '0006_auto_20200303_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmembershiptypes',
            name='membership_type',
            field=models.CharField(choices=[('Smile School English Full', 'Full Plan'), ('SmileSchoolFuture', 'Future Plan'), ('SmileSchoolBasic', 'Basic Plan'), ('None', 'No Plan')], default='SmileSchoolBasic', max_length=30),
        ),
        migrations.AlterField(
            model_name='studentmembershiptypes',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
