# Generated by Django 3.0.3 on 2020-03-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelanding', '0007_auto_20200303_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmembershiptypes',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
    ]
