# Generated by Django 3.0.3 on 2020-03-03 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homelanding', '0008_studentmembershiptypes_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='membership',
            field=models.ForeignKey(default='None', null=True, on_delete=django.db.models.deletion.SET_NULL, to='homelanding.StudentMembershipTypes'),
        ),
        migrations.AlterField(
            model_name='studentmembershiptypes',
            name='membership_type',
            field=models.CharField(choices=[('Smile School English Full', 'Full Plan'), ('SmileSchoolFuture', 'Future Plan'), ('SmileSchoolBasic', 'Basic Plan'), ('None', 'No Plan')], default='None', max_length=30),
        ),
    ]
