# Generated by Django 3.0.3 on 2020-03-03 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homelanding', '0009_auto_20200303_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='membership',
            field=models.ForeignKey(default='None', null=True, on_delete=django.db.models.deletion.SET_NULL, to='homelanding.StudentMembership'),
        ),
    ]
