# Generated by Django 3.0.3 on 2020-03-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelanding', '0012_auto_20200303_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmembershiptypes',
            name='membership_type',
            field=models.CharField(choices=[('Smile School English Full', 'Full Plan'), ('Smile School Future', 'Future Plan'), ('Smile School Basic', 'Basic Plan'), ('None', 'No Plan')], default='None', max_length=50),
        ),
    ]
