# Generated by Django 3.0.3 on 2020-03-03 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homelanding', '0013_auto_20200303_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='membership',
            new_name='membershiptype',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homelanding.StudentSubscription'),
        ),
    ]
