# Generated by Django 3.0.3 on 2020-03-03 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homelanding', '0014_auto_20200303_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmembershiptypes',
            name='stripe_plan_id',
        ),
    ]
