# Generated by Django 3.0.3 on 2020-03-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelanding', '0015_remove_studentmembershiptypes_stripe_plan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmembershiptypes',
            name='stripe_plan_id',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentmembershiptypes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
