# Generated by Django 3.0.3 on 2020-03-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelanding', '0016_auto_20200303_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubscription',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
