# Generated by Django 3.0.3 on 2020-03-03 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homelanding', '0018_auto_20200303_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentsubscription',
            name='user_membership',
        ),
        migrations.RemoveField(
            model_name='studentmembership',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='studentmembership',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studentsubscription',
            name='student_membership',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='membershiptype',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='subscription',
        ),
        migrations.DeleteModel(
            name='ParentMembership',
        ),
        migrations.DeleteModel(
            name='ParentMembershipTypes',
        ),
        migrations.DeleteModel(
            name='ParentSubscription',
        ),
        migrations.DeleteModel(
            name='StudentMembership',
        ),
        migrations.DeleteModel(
            name='StudentMembershipTypes',
        ),
        migrations.DeleteModel(
            name='StudentSubscription',
        ),
    ]
