# Generated by Django 3.0.3 on 2020-03-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelanding', '0019_auto_20200303_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentprofile',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
