# Generated by Django 3.0.3 on 2020-03-04 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studentmemberships', '0003_auto_20200304_0439'),
    ]

    operations = [
        migrations.CreateModel(
            name='FutureCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('allowed_memberships', models.ManyToManyField(to='studentmemberships.FutureStudentMembershipType')),
            ],
        ),
        migrations.CreateModel(
            name='FutureLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=120)),
                ('position', models.IntegerField()),
                ('video_url', models.CharField(max_length=200)),
                ('readinglist_url', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('allowed_memberships', models.ManyToManyField(to='studentmemberships.FutureStudentMembershipType')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.FutureCourse')),
            ],
        ),
        migrations.CreateModel(
            name='EnglishCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('allowed_memberships', models.ManyToManyField(to='studentmemberships.EnglishStudentMembershipType')),
            ],
        ),
        migrations.CreateModel(
            name='EnglihLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=120)),
                ('position', models.IntegerField()),
                ('video_url', models.CharField(max_length=200)),
                ('readinglist_url', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('allowed_memberships', models.ManyToManyField(to='studentmemberships.EnglishStudentMembershipType')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.EnglishCourse')),
            ],
        ),
    ]
