# Generated by Django 3.0.3 on 2020-03-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='englishlesson',
            name='assignment',
            field=models.TextField(blank=True),
        ),
    ]
