# Generated by Django 3.0.3 on 2020-03-04 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentmemberships', '0003_auto_20200304_0439'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnglihLesson',
            new_name='EnglishLesson',
        ),
    ]
