# Generated by Django 3.0.3 on 2020-03-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabularyword',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='vocabularyword',
            name='definition',
            field=models.TextField(null=True),
        ),
    ]
