# Generated by Django 3.0.3 on 2020-03-30 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0003_auto_20200330_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vocabularyword',
            old_name='vocabword',
            new_name='new_word',
        ),
    ]
