# Generated by Django 3.0.10 on 2021-02-01 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_picture', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='users/%d/%m/%y')),
                ('usertype', models.CharField(choices=[('Parent', 'Parent'), ('Child', 'Child'), ('None', 'None')], default='None', max_length=30)),
                ('referredby', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('slug', models.SlugField(blank=True, max_length=30, null=True)),
                ('next_lesson', models.DateField(blank=True, null=True)),
                ('futuretutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tutors.FutureTutor')),
            ],
        ),
    ]
