# Generated by Django 3.0.3 on 2020-03-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepages', '0002_auto_20200315_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='usertype',
            field=models.CharField(choices=[('Parent', 'Parent'), ('Child', 'Child'), ('None', 'None')], default='None', max_length=30),
        ),
    ]
